[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"

  [headers.values]
    Content-Type = "text/html"
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"